name: Testes Django CI

on:
  push:
    branches:
      - novoteste
      - testes-ci
      - main
  pull_request:
    branches:
      - novoteste
      - testes-ci
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: sistema_eleicao
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: sistema_eleicao

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          export DJANGO_SETTINGS_MODULE=sistema_eleicao.settings
          pytest
          
      - name: Gerar CSV com votação simulada
        run: python gerar_csv_votacao.py

